"""empty message

Revision ID: 68e8c12d1ec3
Revises: 224f5ec7dfd8
Create Date: 2023-01-23 23:31:40.466141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e8c12d1ec3'
down_revision = '224f5ec7dfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_transfer_bank_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('transactions_transfer_bank_id_key', ['transfer_bank_id'])

    # ### end Alembic commands ###
