"""empty message

Revision ID: ad1518dcf36a
Revises: fc2bf1dfa34b
Create Date: 2023-01-11 01:30:13.736934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1518dcf36a'
down_revision = 'fc2bf1dfa34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('rut', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('validate_status', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=13), nullable=False))
    op.add_column('user', sa.Column('birthdate', sa.String(length=13), nullable=False))
    op.add_column('user', sa.Column('nationality', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('ocupation', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('monthly_income', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('particular_address', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('department', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['ocupation'])
    op.create_unique_constraint(None, 'user', ['rut'])
    op.create_unique_constraint(None, 'user', ['monthly_income'])
    op.create_unique_constraint(None, 'user', ['particular_address'])
    op.create_unique_constraint(None, 'user', ['department'])
    op.create_unique_constraint(None, 'user', ['first_name'])
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['birthdate'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user', ['nationality'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'department')
    op.drop_column('user', 'particular_address')
    op.drop_column('user', 'monthly_income')
    op.drop_column('user', 'ocupation')
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'validate_status')
    op.drop_column('user', 'rut')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
